apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: mixedcpus-plugin-ds
spec:
  selector:
    matchLabels:
      app: mixedcpus-plugin
  template:
    spec:
      serviceAccountName: mixedcpus-plugin
