apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mixedcpus-plugin

resources:
  - ../default
  - securitycontextconstraint.yaml
  - rbac

patchesStrategicMerge:
  - add_security_perms.yaml
  - add_serviceaccount.yaml
