apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: mixedcpus-plugin-ds
  namespace: mixedcpus-plugin
spec:
  selector:
    matchLabels:
      app: mixedcpus-plugin
  template:
    metadata:
      labels:
        app: mixedcpus-plugin
    spec:
      serviceAccountName: mixedcpus-plugin
      containers:
          - name: mixedcpus-plugin
            image: quay.io/titzhak/mixedcpus
            imagePullPolicy: Always
            command:
              - /bin/mixedcpus
            args:
              - --name=mixedcpus
              - --idx=99
              - --reserved-cpus=0,2,52,54,4,56
            resources:
              requests:
                cpu: 500m
                memory: '100M'
              limits:
                cpu: 500m
                memory: '100M'
            volumeMounts:
              - mountPath: /var/run/nri.sock
                name: nri-sock
            securityContext:
              privileged: true
            env:
            - name: "NODE_NAME"
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
      volumes:
        - name: nri-sock
          hostPath:
            path: /var/run/nri.sock

